### PR TITLE
deepinArtwork

### PR DESCRIPTION
**Pull request by gonzalo2099**
package does not exist currently

### CODE REVIEW

**Comment by oberon2007** [comment]
It does, but is still in unstable branch :)

**Comment by oberon2007** [comment]
I will push an updated version of the profile in a moment...

**Comment by oberon2007** [comment]
Just build the ISO against unstable with ``buildpkg -b unstable`` or set this the standard in your ~/.manjaro-tools.conf

**Comment by oberon2007** [comment]
Just pushed a new version. If login fails try removing the /var dir in overlay-livecd

**Comment by gonzalo2099** [comment]
ok, thnxs for for info

**Comment by oberon2007** [comment]
I am currently uploading a new test-ISO. You can download it later today from here: https://sourceforge.net/projects/manjaro-deepin/files/
At the moment the profile is not in a state you can build it like that. Right now it still needs intervention in the chroot before squashing the image ... But looks like I'm getting somewhere now ;)
Autologin is solved. What I have not figured out, yet is how to pre-define the items in the bar and some other little details - I will post in more details on the forum later.
Meanwhile have fun playing around with it a little! :)

**Comment by gonzalo2099** [comment]
Hi, yesterday i play a bit with deepin profile from git repo and all was
working fine for me, later to try iso in a VM, i installed it on my pc and
i don't get any problem to. Is so cool that you upload a deepin spin, is so
cool desktop.

Thanks so much for your quick reply and your interest with deepin desktop.
Best regards, Gonzalo.

2015-10-18 9:37 GMT+00:00 Bernhard Landauer <notifications@github.com>:

**Comment by oberon2007** [comment]
:-)
Thank you, too, for pushing me again a little I this direction! ;-) :-D

Am 18. Oktober 2015 17:15:29 MESZ, schrieb gonzalo <notifications@github.com>:
>Hi, yesterday i play a bit with deepin profile from git repo and all
>was
>working fine for me, later to try iso in a VM, i installed it on my pc
>and
>i don't get any problem to. Is so cool that you upload a deepin spin,
>is so
>cool desktop.
>
>Thanks so much for your quick reply and your interest with deepin
>desktop.
>Best regards, Gonzalo.
>
>2015-10-18 9:37 GMT+00:00 Bernhard Landauer <notifications@github.com>:
>
>> I am currently uploading a new test-ISO. You can download it later
>today
>> from here: https://sourceforge.net/projects/manjaro-deepin/files/
>> At the moment the profile is not in a state you can build it like
>that.
>> Right now it still needs intervention in the chroot before squashing
>the
>> image ... But looks like I'm getting somewhere now ;)
>> Autologin is solved. What I have not figured out, yet is how to
>pre-define
>> the items in the bar and some other little details - I will post in
>more
>> details on the forum later.
>> Meanwhile have fun playing around with it a little! :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/manjaro/manjaro-tools-iso-profiles/pull/72#issuecomment-148995310>
>> .
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/manjaro/manjaro-tools-iso-profiles/pull/72#issuecomment-149024219

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Pull request closed without merging**
