### PR TITLE
add jwm

### PR DESCRIPTION
**Pull request by oberon2007**
A few little things still need to be packaged away :wink: like **oblogout** and some other stray icons...
@udeved @holmeslinux 
See also https://github.com/manjaro/desktop-settings/pull/41

### CODE REVIEW

**Comment by oberon2007** [comment]
Ah. I only see Holmes's version on his github ... Wait! Coming back later! :stuck_out_tongue_winking_eye:

**Comment by oberon2007** [comment]
ok. It was practically idendical :laughing:

**Comment by holmeslinux** [comment]
these icons are few.
you need to to pack?

**Comment by holmeslinux** [comment]
4 icons (folder Faenza 1 and hicolor 3)

**Comment by oberon2007** [comment]
Yes, it will be clean then. We are trying to move more or less everything out of the profiles ;)
How about we convert **jwm-wallpapers** to **artwork-jwm** and include them there?
Also: Do you really need that black grub screen? Other editions don't have it and grub screen there looks ok still! :wink:

**Comment by holmeslinux** [comment]
hello @oberon2007 
i decided remove these icons and wallpaper black!

**Comment by oberon2007** [comment]
OK! :) [done](https://github.com/oberon2007/manjaro-tools-iso-profiles/commit/b23710e1ecea803ed227efb7868914b1460d4bf3) As I said. We can add them to the wallpaper package if you still want to use them!

**Comment by oberon2007** [comment]
Hey! Looks like we're ready to merge now :smiley: Welcome back!!

**Comment by oberon2007** [comment]
Ah. Forgot about the oblogout theme and your jwm-buttons. We'll package those still, ok!?

**Pull request merged**
