### PR TITLE
[xfce-openrc] profile updates

### PR DESCRIPTION
**Pull request by aadityabagga**
Anyone care to merge it in?

### CODE REVIEW

**Comment by philmmanjaro** [comment]
@aadityabagga : please rebase of our current development branch. Seems you have some changes regarding KDE5 profile. Therefor we can't merge it like that.

**Comment by aadityabagga** [comment]
Hey Phil,

I merged it today against the devel profile, so all the changes seem to be in :)

I may have made a mistake in submitting it against the master branch, I will close and open another one for the devel branch.

**Comment by aadityabagga** [comment]
New pull sent, sorry for the confusion.
https://github.com/manjaro/manjaro-tools-iso-profiles/pull/18

**Comment by aadityabagga** [comment]
I did a git clone of the manjaro-tools repo, and was able to successfully merge my changes.
http://pastebin.com/hmkPPV8B

So pull https://github.com/manjaro/manjaro-tools-iso-profiles/pull/18 seems to work.

**Pull request closed without merging**
