### PR TITLE
Update bpswm profile

### PR DESCRIPTION
**Pull request by Chrysostomus**

### CODE REVIEW

**Comment by oberon2007** [comment]
Do you need that in stable now for the ISO, too?

**Comment by Chrysostomus** [comment]
Reference unclear. Do I need what in stable?

**Comment by oberon2007** [comment]
Sorry. Forget that! ;D I thought this was the bspwm-scripts pkg. I'm tired! Good night! ;)

**Comment by Chrysostomus** [comment]
Good night!

**Pull request merged**
