### PR TITLE
updating package list

### PR DESCRIPTION
**Pull request by gonzalo2099**
fix an error

### CODE REVIEW

**Comment by philmmanjaro** [comment]
which error does it create?

**Comment by gonzalo2099** [comment]
Tells you that the file alrready exist and abort the iso build

**Comment by philmmanjaro** [comment]
Which file does it claim to exist already?

**Comment by gonzalo2099** [comment]
Yaourt, if a package is alrready installed in iso-build by default and is
installed again by package list gives you that error.

**Comment by philmmanjaro** [comment]
I don't think **yaourt** get installed by default. Please check **/var/lib/manjaro-tools/buildiso/pantheon/x86_64/root-image/root-image-pkgs.txt**. Which exact file does it complain about?

**Comment by gonzalo2099** [comment]
Also there are some packages that are needed to put a comment symbol
because they are not availabe on stable repos.

Best regargs.

**Comment by philmmanjaro** [comment]
Which packages do you mean?

**Comment by philmmanjaro** [comment]
This profile uses some custom repos:
```
[pantheon]
SigLevel = Optional
Server = http://pkgbuild.com/~alucryd/$repo/$arch

#[testing]
#SigLevel = Optional TrustAll
#Server = http://download.tuxfamily.org/repoarch/testing/$arch

[pantheonrepo]
SigLevel = Optional TrustAll
#Server = https://sourceforge.net/projects/pantheonrepo/files/$arch/
Server = http://download.tuxfamily.org/repoarch/pantheonrepo/$arch
```

**Comment by gonzalo2099** [comment]
When i try to build iso gives me this error, and the only way that i got to
fix it is deleting the package from package list. I'm using manjaro-tools
not manjaro-iso.

**Comment by philmmanjaro** [comment]
Please post me the error you get. Which version of **manjaro-tools** do you use?

**Comment by gonzalo2099** [comment]
Yes, i saw that use some external repo, in pkg list there is a package that
does not exist on alucryd repo.

**Comment by philmmanjaro** [comment]
Ok, makes sense. @Ste74: Ciao Steve , puoi controllare il tuo profilo . Sembra che alcuni pacchetti modificati.

**Comment by gonzalo2099** [comment]
I dont want that someone gets angry because i made a pull request and
change the job. I just did cos i saw and wanted to fix it, no more ;)

**Comment by philmmanjaro** [comment]
@gonzalo2099: all is fine. Let the maintainer @Ste74 check it also ...

**Comment by gonzalo2099** [comment]
Check attachment when you got time, i disable yaourt on package list but
appear installed in iso by default.

**Comment by philmmanjaro** [comment]
There is no attachment. Please share a link.

**Comment by gonzalo2099** [comment]
here you got  link
https://cloud.openmailbox.org/index.php/s/AFRVsjoRRTRHWZB

**Comment by Ste74** [comment]
Hi @philmanjaro @gonzalo2099 , this afternon recheck the pkg list , problem is in alucryd repo, it remove one day ago a pkg , i have to investigate why are removed. Yaourt is not the problem ;)

**Comment by Ste74** [comment]
This solve your problem https://github.com/manjaro/manjaro-tools-iso-profiles/commit/2cbbcc97b2a456a6828045448e88419714c4b703 remember to use unstable branch for build iso .
Thank you for your interesting :wink:

**Comment by gonzalo2099** [comment]
Thanks for information, i will use unstable ;)

**Pull request closed without merging**
