### PR TITLE
LXQT fails to build, rewritten and deleted user-repos.conf file

### PR DESCRIPTION
**Pull request by FabioLolix**
LXQT profile fails to build,
I rewritten it and deleted user-repos.conf file

> ==> Creating install root at /var/lib/manjaro-tools/buildiso/lxqt/x86_64/lxqt-image
  -> Installing packages to /var/lib/manjaro-tools/buildiso/lxqt/x86_64/lxqt-image
:: Synchronizing package databases...
 core                                                                                     137.8 KiB  61.2K/s 00:02 [####################################################################] 100%
 extra                                                                                   1937.8 KiB   294K/s 00:07 [####################################################################] 100%
 community                                                                                  3.9 MiB  1976K/s 00:02 [####################################################################] 100%
 multilib                                                                                 185.4 KiB  3.42M/s 00:00 [####################################################################] 100%
 infinality-bundle                                                                          4.3 KiB  0.00B/s 00:00 [####################################################################] 100%
 manjaro-lxqt                                                                               9.3 KiB  2.28M/s 00:00 [####################################################################] 100%
error: target not found: abiword-3.x-gtk2
error: target not found: compton-conf-git
error: target not found: liblxqt-mount
error: target not found: liboobs
error: target not found: mediterraneanlxqt
error: target not found: mpv-light
error: target not found: qarma-git
error: target not found: qlipper-qt5-git
error: target not found: screengrab-git
error: target not found: speedcrunch-git
error: target not found: system-tools-backends
==> ERROR: Failed to install packages to new root
==> ERROR: Failed to install all packages
==> ERROR: A failure occurred in make_image_custom().
    Aborting...

### CODE REVIEW

**Comment by philmmanjaro** [comment]
@udeved: can you check against your still maintained **lxqt-minimal** profile if this makes sense? **user-repos** we had removed from our support, so it might work with these changes.

**Comment by Ste74** [comment]
I think also @Esclapion have to check because the last iso use this custom repo so the last iso can`t update this packages ?

**Comment by Esclapion** [comment]
Package-Lxqt updated, but if you remove user-repos.conf, all references to the external repo will continue to be not found.

**Comment by Esclapion** [comment]
I read your pull request, and it's not done for that, I think. You put your own choices, you replace octopi (qt5) by pamac (gtk), etc... If everybody does so, i don't know how to solve that.
You put your theme and your icons, etc...
I try to avoid use of gst plugins with use of ffmepg, and you add them.

We can discuss, if you want, by cons.

**Comment by Esclapion** [comment]
qupzilla based on the new qt5-webengine was also my choice, but it seems than it don't work with nouveau driver (to verify). If yes, too many users have nouveau drivers to push it.

Else, I find too than it's an very, very good browser. You can also use with him adobe-flashplugin, who works perfectly. For html5, it's a lot better than FF and not far of chromium.

**Comment by Ste74** [comment]
@Esclapion, if you want and if you can maintain the pkgbuilds i already say (also oberon) is not a problem to push in our repo the pkg needed (excluse infinity for license problem)... is not problem helping to do the desktop-settings pkgs.....
Il 19/ago/2016 11:18, Esclapion <notifications@github.com> ha scritto:qupzilla based on the new qt5-webengine was also my choice, but it seems than it don't work with nouveau driver (to verify). If yes, too many users have nouveau drivers to push it.

Else, I find too than it's an very, very good browser. You can also use with him adobe-flashplugin, who works perfectly. For html5, it's a lot better than FF and not far of chromium.

**Comment by Esclapion** [comment]
@Ste74 , thanks, I note ;) For the moment, I wait for lxqt 0.11, doing slowly some tries.

I recently loved my mirror to Strit's server and limited the number of external packages.

**Comment by Ste74** [comment]
When you want, no problem here mate ;)
Il 19/ago/2016 13:01, Esclapion <notifications@github.com> ha scritto:@Ste74 , thanks, I note ;) For the moment, I wait for lxqt 0.11, doing slowly some tries.

I recently loved my mirror to Strit's server and limited the number of external packages.

**Comment by Ste74** [comment]
Closed with Esclapion update

**Comment by FabioLolix** [comment]
Hello @Esclapion 
I'm sorry for my noobness.
I've made it in a rush and naive, I didn't mean to push this or that software/theme.
Didn't know about octopi and ffmpeg, sorry for my bad choice.

I can try Qupzilla on nouveau driver soon.

**Pull request closed without merging**
