### PR TITLE
Gnome autostart

### PR DESCRIPTION
**Pull request by anika200**
Adding a desktop file to the ~/.config/autostart folder to auto start yelp help program so new users can get information on how to use Gnome.

### CODE REVIEW

**Comment by anika200** [comment]
Sorry, this is my first push and I am working through learning github and git. If fact I have already created new branch and removed this from my master so you may see another push that looks the same.

**Comment by korrode** [comment]
Yelp is Gnome's first-run wizard?
Does it disable autostarting after the first run?
(sorry i'm not in a position to test this myself atm...)

tagging @philmmanjaro

**Comment by anika200** [comment]
Yelp is Gnome Help system, very comprehensive instructions on how to use the Gnome desktop environment. It will not disable after the first run but I see that as an advantage because it takes more than a couple reads to learn Gnome. It can easily be closed via the x button in the window title bar.
Having the help system open at start should help new users more easily learn how to use Gnome which is not really that intuitive in my humble opinion.

**Comment by philmmanjaro** [comment]
For me it makes no sense to have **yelp** autostarted. Dismissed.

**Pull request closed without merging**
