### PR TITLE
Update bspwm profile

### PR DESCRIPTION
**Pull request by Chrysostomus**

### CODE REVIEW

**Comment by Ste74** [comment]
Hi @Chrysostomus .. what version of manjaro tools you use for this profile? 0.13 o the new in git 0.14 ?

**Comment by Chrysostomus** [comment]
No idea. What are the requirements for 0.14?

**Comment by udeved** [comment]
Do you use repo tools @Chrysostomus ?

**Comment by Chrysostomus** [comment]
Would that be boxit? No.

**Comment by Ste74** [comment]
If you use manjaro-tools 0.13.x series you have to use the 16.10-profiles instead of the master branch

**Comment by Chrysostomus** [comment]
Okay. And I can use the master branch with 0.14?

**Comment by Ste74** [comment]
Theorically yes .. but is better if you use the new repo` iso-profiles `.. check it https://github.com/manjaro/iso-profiles .. all new set release for Gellevara is here .. but if you prefer use the old for now you can but with mt 0.13 and 16.10-profiles branch ..

**Comment by Chrysostomus** [comment]
Хорошо. I'll migrate to iso-profiles. Anything I should know about the process?

**Comment by Ste74** [comment]
No you can export your profile in iso-profiles need only little adjustment .. check our new profiles to understand :smile: ... remember to use with mt 0.14 git version ( if you have copy manjaro-tools.conf in your home check also the new schema .. ) 😉

**Comment by Chrysostomus** [comment]
... Could you still merge the updates here? I'm working on experimental installer script (https://forum.manjaro.org/t/experience-with-architect-linux-or-other-cli-installers/14964/63)  that grabs packages from this repo.

**Comment by Ste74** [comment]
Yes i can .. but are you have tested this? work for you ? The profiles ready for build are the 16.10-profiles ( https://github.com/manjaro/manjaro-tools-iso-profiles/tree/16.10-Profiles ) and are the profiles present in Boxit ..

**Comment by Ste74** [comment]
I suggest to copy this packages into the branch 16.10-profiles .. nothing change only the checkout

**Comment by Chrysostomus** [comment]
Terminal + browser

**Comment by Ste74** [comment]
https://git-scm.com/docs/git-checkout

**Pull request closed without merging**
