### PR TITLE
Updated Openbox to what we are currently working on.

### PR DESCRIPTION
**Pull request by XiKuuKy**

### CODE REVIEW

**Comment by philmmanjaro** [comment]
It is great that you guys work on it. 

However I don't see any sense in adding a icon theme into your overlay (usr/share/icons/masalla). Same goes for the cursor theme (usr/share/icons/Breeze-Snow/cursors) and fonts (usr/share/fonts/TTF/{Coda-#,Roboto-#})

I suggest to remove them and request a community package instead.

**Comment by XiKuuKy** [comment]
Okay, I can do that.

**Comment by XiKuuKy** [comment]
How do I request a community package?

**Comment by philmmanjaro** [comment]
Either open an [issue](https://github.com/manjaro/packages-community/issues) or fork the repo and provide your PKGBUILDs. Check the AUR if those wanted icons, fonts and cursors are available there.

**Comment by XiKuuKy** [comment]
We're moving to Vibrancy. I have built the PKG and made the local repo, will add soon. Thanks for your patience!

**Comment by philmmanjaro** [comment]
Well, I still see icons, fonts and cursors in this profile. Is a cleanup or a rebase planed for this profile?

**Comment by XiKuuKy** [comment]
We are pulling some ideas together. Give us a bit. Sorry it's taking so long. I don't really know what a cleanup or rebase is but right now we're trying to start a shape. Our lead mainatainer Holmes has moved to Manjaro Jwm and left me to make 0.9.0 and I picked up Withjaro to help me out and we have agreed on a bit of a redesign. Sorry again.

 - Xikuuky

**Comment by philmmanjaro** [comment]
No problem at all. Take all the time you need. With a cleanup I mean to remove the folders for icons, fonts and cursors from your profile and provide them as packages. It is not good to have binaries in a git repository. Also it is always better to provide those as a package so people can uninstall it, if they want to do so ...

**Comment by XiKuuKy** [comment]
Got it. Have a great night!

 - Xikuuky

**Comment by philmmanjaro** [comment]
Seems nothing happened so far here. I still see some themes in your files ...

**Comment by Ste74** [comment]
@XiKuuKy have you follow the philm suggestion ?

**Comment by XiKuuKy** [comment]
Check the forums. Someone else took over. I'm done.

**Comment by oberon2007** [comment]
I don't see what you mean. Who do you would have taken over?

**Comment by XiKuuKy** [comment]
Ask them, I can't do this. My life is super complicated right now.

**Comment by oberon2007** [comment]
I'm sorry. I don't know whom you mean... Take care anyway.

**Comment by philmmanjaro** [comment]
Ok, fine. Thx anyway.

**Comment by excalibur1234** [comment]
@oberon2007: look at this (and the following) forum post by xikuuky:
https://forum.manjaro.org/index.php?topic=25277.msg231350#msg231350

it looks like Chrysostomus and/or mxx will MAYBE do at least some work with manjaro openbox in the future.

**Comment by oberon2007** [comment]
Thanks, @excalibur1234 ! So everything looks peaceful and in order. :) This sounded a bit discomforting for me at first. I think I just did not read the right tone in @XiKuuKy 's message here ;)

**Pull request closed without merging**
