### PR TITLE
Add gnome-online-accounts so goa works again

### PR DESCRIPTION
**Pull request by boredland**
I'd additionally propose to add evolution, since it provides a good goa-integration into one single tool instead of (the commented) gnome-contacts etcpp

### CODE REVIEW

**Comment by udeved** [comment]
This repo has been deprecated.

New profile are here
https://github.com/manjaro/iso-profiles

**Comment by boredland** [comment]
I thought the one you linked was for the upcoming 17.0 only.

**Comment by udeved** [comment]
We don't work in the old repo any longer. Would be useless to merge there, 17.0 will be release next days or so.
Gnome maintainer will decide about merge in new repo @Ste74

**Comment by boredland** [comment]
Ah, well. I understand!

**Pull request closed without merging**
