### PR TITLE
[dev] new profile 2015.08

### PR DESCRIPTION
**Pull request by Ste74**
Profile for dev release 2015.08

### CODE REVIEW

**Comment by Kirek** [comment]
Seems fine but you need to remove all ".directory" files, there are some outside your profile too!
also at least "/etc/skel/.dbus/" and "/etc/skel/.config/pulse/" need to be removed.

**Comment by Ste74** [comment]
Hi Ramon .. some mistakes I still do it ;-)
have problem with smartgit .. have to delete the pull request to solve ?
schermata5

**Comment by Kirek** [comment]
Just push your changes to github and the pull request will be automatically updated

**Comment by Ste74** [comment]
I was not able to load the changes with SmartGit in my github repo . Now I did not understand how I managed but there

**Pull request merged**
