### PR TITLE
Correct last commit . User is set to manjaro,clean config user

### PR DESCRIPTION
**Pull request by Ste74**
I have rebuild the list of packages of pantheon and set user to "manjaro" and  password to "manjaro" in line with master iso .
I have rebuild an iso with this changes . Is ok but i have a problem with dbus i think . In dbus-editor not appear the key org . I don't understand why. 
Stefano

### CODE REVIEW

**Comment by Kirek** [comment]
Please clean up it
Remove everything under skel/.config/pulse and I'm pretty sure everything under skel/.local can be deleted too.
Unless you made some modifications to midori, everything under skel/.config/midori can me removed, but the "pantheon/pantheon-overlay/etc/skel/.config/midori/config" file.
This other files too:
pantheon/pantheon-overlay/etc/skel/.config/user-dirs.dirs
pantheon/pantheon-overlay/etc/skel/.config/manjaro/manjaro-settings-manager-daemon.conf
pantheon/pantheon-overlay/etc/skel/.config/gtk-3.0/bookmarks 

You don't need to cancel the pull request, make you changes in you repo and it would show up automatically here.

**Comment by Ste74** [comment]
I have  modified the home page of midori in home page of manjaro

**Comment by philmmanjaro** [comment]
I think **pantheon/pantheon-overlay/usr/share/xfce4** is not needed here ...

**Comment by Ste74** [comment]
Aaargh i not see this i delete now ....

**Pull request merged**
