### PR TITLE
Update Packages-Bspwm

### PR DESCRIPTION
**Pull request by Chrysostomus**
Add clonezilla and mhwd-chroot-extended

### CODE REVIEW

**Comment by Ste74** [comment]
Hi , this not working with other disk ? I can't test.. 
https://github.com/manjaro/manjaro-tools#5-manjaro-chroot

**Comment by Chrysostomus** [comment]
I haven't tested it, I added the the extended version at the request of a user that said that it supports more hardware. See here: https://forum.manjaro.org/index.php?topic=32902.new;topicseen#new

**Comment by udeved** [comment]
What does the extended version of mhwd-chroot?

**Comment by Ste74** [comment]
@udeved see here
https://forum.manjaro.org/index.php?topic=21472.msg265035#msg265035

**Comment by Ste74** [comment]
@udeved , @Chrysostomus in my head i think one pkg for one app i.e. manjaro-chroot can do chroot into  NVMe storage ? If yes i think this pkg from aur is not needed...

**Comment by Ste74** [comment]
Well .. mhwd-chroot-extended is not in our community repo .. you not provide an additional server to provide it .. if you want add this i can but i need to be sure this functionality is not provide to manjaro-chroot . I ask in the forum help to test manjaro-chroot with NVMe .. 
https://forum.manjaro.org/index.php?topic=32902.msg272336#msg272336

**Comment by udeved** [comment]
How many people use the wrapper to chroot in NVM?
I believe its small, and those who do, don't need a wrapper. 
So from my point of view, its useless feature, I'd find proper lvm and raid support more important.

**Comment by Ste74** [comment]
I also not know the NVMe disk :stuck_out_tongue_winking_eye:

**Comment by Chrysostomus** [comment]
I'm not even sure what nvm is. I just complied with a user request. Maybe it is better not to have if it isn't in the repos.

**Comment by Ste74** [comment]
if you agree, then you correct the request so as to leave only clonezilla :wink:

**Comment by Chrysostomus** [comment]
Done

**Comment by Ste74** [comment]
:)

**Pull request merged**
